# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppStructure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppStructure
	pod 'Alamofire', '~> 5.2'

end
